# Change these first
owner: crzbread # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Blog
    url: https://blog.dbb.tw
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.dbb.tw
  # baseUrl: /your-repo-name
  logoUrl: https://github.com/crzbread.png
  name: DBB's 網站監控
  introTitle: "**網站狀態頁面** - 實時監控與可用性報告"
  introMessage: 這是我們的狀態頁，使用 **GitHub Actions** 與 **Upptime** 即時監控網站狀態。查看 [GitHub 倉庫](https://github.com/crzbread) 了解更多。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/crzbread

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
